# Generated by Django 4.2.1 on 2023-05-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_city",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Название населенного пункта",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Название населенного пункта",
                "verbose_name_plural": "Название населенных пунктов",
            },
        ),
        migrations.CreateModel(
            name="Programming_language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_city",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Язык програмирования"
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Язык програмирования",
                "verbose_name_plural": "Языки програмирования",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urls", models.URLField(unique=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Заголовок компании"),
                ),
                ("company", models.CharField(max_length=250, verbose_name="Компания")),
                ("description", models.TextField(verbose_name="Описание вакансии")),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraping.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraping.programming_language",
                        verbose_name="Язык програмирования",
                    ),
                ),
            ],
            options={"verbose_name": "Вакансия", "verbose_name_plural": "Вакансии",},
        ),
    ]
